sonar.projectKey=DeskcorpGit_apis-description
sonar.projectName=APIs Description Portal

sonar.sources=src

sonar.exclusions=\
  node_modules/**,\
  dist/**,\
  **/*.test.ts,\
  **/*.spec.ts,\
  **/coverage/**

# Configurações TypeScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding dos arquivos
sonar.sourceEncoding=UTF-8
